/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedTryoutIndexRouteImport } from './routes/_authed/tryout/index'
import { Route as AuthedSuplementIndexRouteImport } from './routes/_authed/suplement/index'
import { Route as AuthedQuizIndexRouteImport } from './routes/_authed/quiz/index'
import { Route as AuthedLearningPathIndexRouteImport } from './routes/_authed/learning-path/index'
import { Route as AuthedLeaderboardIndexRouteImport } from './routes/_authed/leaderboard/index'
import { Route as AuthedGrammarIndexRouteImport } from './routes/_authed/grammar/index'
import { Route as AuthedFlashcardIndexRouteImport } from './routes/_authed/flashcard/index'
import { Route as AuthedDashboardIndexRouteImport } from './routes/_authed/dashboard/index'
import { Route as AuthRegisterIndexRouteImport } from './routes/_auth/register/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as AuthForgotPasswordIndexRouteImport } from './routes/_auth/forgot-password/index'
import { Route as AuthedManagementTryoutIndexRouteImport } from './routes/_authed/management/tryout/index'
import { Route as AuthedManagementSuplementIndexRouteImport } from './routes/_authed/management/suplement/index'
import { Route as AuthedManagementQuizIndexRouteImport } from './routes/_authed/management/quiz/index'
import { Route as AuthedManagementLearningPathIndexRouteImport } from './routes/_authed/management/learning-path/index'
import { Route as AuthedManagementGrammarIndexRouteImport } from './routes/_authed/management/grammar/index'
import { Route as AuthedManagementFlashcardIndexRouteImport } from './routes/_authed/management/flashcard/index'
import { Route as AuthedManagementBootcampIndexRouteImport } from './routes/_authed/management/bootcamp/index'
import { Route as AuthedAdministrationUserIndexRouteImport } from './routes/_authed/administration/user/index'
import { Route as AuthedAdministrationStaffIndexRouteImport } from './routes/_authed/administration/staff/index'
import { Route as AuthedAdministrationPricingIndexRouteImport } from './routes/_authed/administration/pricing/index'
import { Route as AuthedManagementTryoutCreateRouteImport } from './routes/_authed/management/tryout/create'
import { Route as AuthedManagementSuplementCreateRouteImport } from './routes/_authed/management/suplement/create'
import { Route as AuthedManagementQuizCreateRouteImport } from './routes/_authed/management/quiz/create'
import { Route as AuthedManagementFlashcardCreateRouteImport } from './routes/_authed/management/flashcard/create'
import { Route as AuthedManagementBootcampCreateRouteImport } from './routes/_authed/management/bootcamp/create'
import { Route as AuthedAdministrationUserCreateRouteImport } from './routes/_authed/administration/user/create'
import { Route as AuthedAdministrationStaffCreateRouteImport } from './routes/_authed/administration/staff/create'
import { Route as AuthedAdministrationPricingCreateRouteImport } from './routes/_authed/administration/pricing/create'
import { Route as AuthedManagementLearningPathIdIndexRouteImport } from './routes/_authed/management/learning-path/$id/index'
import { Route as AuthedManagementGrammarIdIndexRouteImport } from './routes/_authed/management/grammar/$id/index'
import { Route as AuthedManagementGrammarIdAddRouteImport } from './routes/_authed/management/grammar/$id/add'
import { Route as AuthedManagementFlashcardCardDeckIdEditRouteImport } from './routes/_authed/management/flashcard/$cardDeckId/edit'
import { Route as AuthedManagementFlashcardCardDeckIdAddRouteImport } from './routes/_authed/management/flashcard/$cardDeckId/add'

const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTryoutIndexRoute = AuthedTryoutIndexRouteImport.update({
  id: '/tryout/',
  path: '/tryout/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSuplementIndexRoute = AuthedSuplementIndexRouteImport.update({
  id: '/suplement/',
  path: '/suplement/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedQuizIndexRoute = AuthedQuizIndexRouteImport.update({
  id: '/quiz/',
  path: '/quiz/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedLearningPathIndexRoute = AuthedLearningPathIndexRouteImport.update({
  id: '/learning-path/',
  path: '/learning-path/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedLeaderboardIndexRoute = AuthedLeaderboardIndexRouteImport.update({
  id: '/leaderboard/',
  path: '/leaderboard/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedGrammarIndexRoute = AuthedGrammarIndexRouteImport.update({
  id: '/grammar/',
  path: '/grammar/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedFlashcardIndexRoute = AuthedFlashcardIndexRouteImport.update({
  id: '/flashcard/',
  path: '/flashcard/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedDashboardIndexRoute = AuthedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/_auth/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/_auth/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordIndexRoute = AuthForgotPasswordIndexRouteImport.update({
  id: '/_auth/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedManagementTryoutIndexRoute =
  AuthedManagementTryoutIndexRouteImport.update({
    id: '/management/tryout/',
    path: '/management/tryout/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedManagementSuplementIndexRoute =
  AuthedManagementSuplementIndexRouteImport.update({
    id: '/management/suplement/',
    path: '/management/suplement/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedManagementQuizIndexRoute =
  AuthedManagementQuizIndexRouteImport.update({
    id: '/management/quiz/',
    path: '/management/quiz/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedManagementLearningPathIndexRoute =
  AuthedManagementLearningPathIndexRouteImport.update({
    id: '/management/learning-path/',
    path: '/management/learning-path/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedManagementGrammarIndexRoute =
  AuthedManagementGrammarIndexRouteImport.update({
    id: '/management/grammar/',
    path: '/management/grammar/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedManagementFlashcardIndexRoute =
  AuthedManagementFlashcardIndexRouteImport.update({
    id: '/management/flashcard/',
    path: '/management/flashcard/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedManagementBootcampIndexRoute =
  AuthedManagementBootcampIndexRouteImport.update({
    id: '/management/bootcamp/',
    path: '/management/bootcamp/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedAdministrationUserIndexRoute =
  AuthedAdministrationUserIndexRouteImport.update({
    id: '/administration/user/',
    path: '/administration/user/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedAdministrationStaffIndexRoute =
  AuthedAdministrationStaffIndexRouteImport.update({
    id: '/administration/staff/',
    path: '/administration/staff/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedAdministrationPricingIndexRoute =
  AuthedAdministrationPricingIndexRouteImport.update({
    id: '/administration/pricing/',
    path: '/administration/pricing/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedManagementTryoutCreateRoute =
  AuthedManagementTryoutCreateRouteImport.update({
    id: '/management/tryout/create',
    path: '/management/tryout/create',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedManagementSuplementCreateRoute =
  AuthedManagementSuplementCreateRouteImport.update({
    id: '/management/suplement/create',
    path: '/management/suplement/create',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedManagementQuizCreateRoute =
  AuthedManagementQuizCreateRouteImport.update({
    id: '/management/quiz/create',
    path: '/management/quiz/create',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedManagementFlashcardCreateRoute =
  AuthedManagementFlashcardCreateRouteImport.update({
    id: '/management/flashcard/create',
    path: '/management/flashcard/create',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedManagementBootcampCreateRoute =
  AuthedManagementBootcampCreateRouteImport.update({
    id: '/management/bootcamp/create',
    path: '/management/bootcamp/create',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedAdministrationUserCreateRoute =
  AuthedAdministrationUserCreateRouteImport.update({
    id: '/administration/user/create',
    path: '/administration/user/create',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedAdministrationStaffCreateRoute =
  AuthedAdministrationStaffCreateRouteImport.update({
    id: '/administration/staff/create',
    path: '/administration/staff/create',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedAdministrationPricingCreateRoute =
  AuthedAdministrationPricingCreateRouteImport.update({
    id: '/administration/pricing/create',
    path: '/administration/pricing/create',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedManagementLearningPathIdIndexRoute =
  AuthedManagementLearningPathIdIndexRouteImport.update({
    id: '/management/learning-path/$id/',
    path: '/management/learning-path/$id/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedManagementGrammarIdIndexRoute =
  AuthedManagementGrammarIdIndexRouteImport.update({
    id: '/management/grammar/$id/',
    path: '/management/grammar/$id/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedManagementGrammarIdAddRoute =
  AuthedManagementGrammarIdAddRouteImport.update({
    id: '/management/grammar/$id/add',
    path: '/management/grammar/$id/add',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedManagementFlashcardCardDeckIdEditRoute =
  AuthedManagementFlashcardCardDeckIdEditRouteImport.update({
    id: '/management/flashcard/$cardDeckId/edit',
    path: '/management/flashcard/$cardDeckId/edit',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedManagementFlashcardCardDeckIdAddRoute =
  AuthedManagementFlashcardCardDeckIdAddRouteImport.update({
    id: '/management/flashcard/$cardDeckId/add',
    path: '/management/flashcard/$cardDeckId/add',
    getParentRoute: () => AuthedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/register': typeof AuthRegisterIndexRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/flashcard': typeof AuthedFlashcardIndexRoute
  '/grammar': typeof AuthedGrammarIndexRoute
  '/leaderboard': typeof AuthedLeaderboardIndexRoute
  '/learning-path': typeof AuthedLearningPathIndexRoute
  '/quiz': typeof AuthedQuizIndexRoute
  '/suplement': typeof AuthedSuplementIndexRoute
  '/tryout': typeof AuthedTryoutIndexRoute
  '/administration/pricing/create': typeof AuthedAdministrationPricingCreateRoute
  '/administration/staff/create': typeof AuthedAdministrationStaffCreateRoute
  '/administration/user/create': typeof AuthedAdministrationUserCreateRoute
  '/management/bootcamp/create': typeof AuthedManagementBootcampCreateRoute
  '/management/flashcard/create': typeof AuthedManagementFlashcardCreateRoute
  '/management/quiz/create': typeof AuthedManagementQuizCreateRoute
  '/management/suplement/create': typeof AuthedManagementSuplementCreateRoute
  '/management/tryout/create': typeof AuthedManagementTryoutCreateRoute
  '/administration/pricing': typeof AuthedAdministrationPricingIndexRoute
  '/administration/staff': typeof AuthedAdministrationStaffIndexRoute
  '/administration/user': typeof AuthedAdministrationUserIndexRoute
  '/management/bootcamp': typeof AuthedManagementBootcampIndexRoute
  '/management/flashcard': typeof AuthedManagementFlashcardIndexRoute
  '/management/grammar': typeof AuthedManagementGrammarIndexRoute
  '/management/learning-path': typeof AuthedManagementLearningPathIndexRoute
  '/management/quiz': typeof AuthedManagementQuizIndexRoute
  '/management/suplement': typeof AuthedManagementSuplementIndexRoute
  '/management/tryout': typeof AuthedManagementTryoutIndexRoute
  '/management/flashcard/$cardDeckId/add': typeof AuthedManagementFlashcardCardDeckIdAddRoute
  '/management/flashcard/$cardDeckId/edit': typeof AuthedManagementFlashcardCardDeckIdEditRoute
  '/management/grammar/$id/add': typeof AuthedManagementGrammarIdAddRoute
  '/management/grammar/$id': typeof AuthedManagementGrammarIdIndexRoute
  '/management/learning-path/$id': typeof AuthedManagementLearningPathIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/register': typeof AuthRegisterIndexRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/flashcard': typeof AuthedFlashcardIndexRoute
  '/grammar': typeof AuthedGrammarIndexRoute
  '/leaderboard': typeof AuthedLeaderboardIndexRoute
  '/learning-path': typeof AuthedLearningPathIndexRoute
  '/quiz': typeof AuthedQuizIndexRoute
  '/suplement': typeof AuthedSuplementIndexRoute
  '/tryout': typeof AuthedTryoutIndexRoute
  '/administration/pricing/create': typeof AuthedAdministrationPricingCreateRoute
  '/administration/staff/create': typeof AuthedAdministrationStaffCreateRoute
  '/administration/user/create': typeof AuthedAdministrationUserCreateRoute
  '/management/bootcamp/create': typeof AuthedManagementBootcampCreateRoute
  '/management/flashcard/create': typeof AuthedManagementFlashcardCreateRoute
  '/management/quiz/create': typeof AuthedManagementQuizCreateRoute
  '/management/suplement/create': typeof AuthedManagementSuplementCreateRoute
  '/management/tryout/create': typeof AuthedManagementTryoutCreateRoute
  '/administration/pricing': typeof AuthedAdministrationPricingIndexRoute
  '/administration/staff': typeof AuthedAdministrationStaffIndexRoute
  '/administration/user': typeof AuthedAdministrationUserIndexRoute
  '/management/bootcamp': typeof AuthedManagementBootcampIndexRoute
  '/management/flashcard': typeof AuthedManagementFlashcardIndexRoute
  '/management/grammar': typeof AuthedManagementGrammarIndexRoute
  '/management/learning-path': typeof AuthedManagementLearningPathIndexRoute
  '/management/quiz': typeof AuthedManagementQuizIndexRoute
  '/management/suplement': typeof AuthedManagementSuplementIndexRoute
  '/management/tryout': typeof AuthedManagementTryoutIndexRoute
  '/management/flashcard/$cardDeckId/add': typeof AuthedManagementFlashcardCardDeckIdAddRoute
  '/management/flashcard/$cardDeckId/edit': typeof AuthedManagementFlashcardCardDeckIdEditRoute
  '/management/grammar/$id/add': typeof AuthedManagementGrammarIdAddRoute
  '/management/grammar/$id': typeof AuthedManagementGrammarIdIndexRoute
  '/management/learning-path/$id': typeof AuthedManagementLearningPathIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/_auth/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/register/': typeof AuthRegisterIndexRoute
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
  '/_authed/flashcard/': typeof AuthedFlashcardIndexRoute
  '/_authed/grammar/': typeof AuthedGrammarIndexRoute
  '/_authed/leaderboard/': typeof AuthedLeaderboardIndexRoute
  '/_authed/learning-path/': typeof AuthedLearningPathIndexRoute
  '/_authed/quiz/': typeof AuthedQuizIndexRoute
  '/_authed/suplement/': typeof AuthedSuplementIndexRoute
  '/_authed/tryout/': typeof AuthedTryoutIndexRoute
  '/_authed/administration/pricing/create': typeof AuthedAdministrationPricingCreateRoute
  '/_authed/administration/staff/create': typeof AuthedAdministrationStaffCreateRoute
  '/_authed/administration/user/create': typeof AuthedAdministrationUserCreateRoute
  '/_authed/management/bootcamp/create': typeof AuthedManagementBootcampCreateRoute
  '/_authed/management/flashcard/create': typeof AuthedManagementFlashcardCreateRoute
  '/_authed/management/quiz/create': typeof AuthedManagementQuizCreateRoute
  '/_authed/management/suplement/create': typeof AuthedManagementSuplementCreateRoute
  '/_authed/management/tryout/create': typeof AuthedManagementTryoutCreateRoute
  '/_authed/administration/pricing/': typeof AuthedAdministrationPricingIndexRoute
  '/_authed/administration/staff/': typeof AuthedAdministrationStaffIndexRoute
  '/_authed/administration/user/': typeof AuthedAdministrationUserIndexRoute
  '/_authed/management/bootcamp/': typeof AuthedManagementBootcampIndexRoute
  '/_authed/management/flashcard/': typeof AuthedManagementFlashcardIndexRoute
  '/_authed/management/grammar/': typeof AuthedManagementGrammarIndexRoute
  '/_authed/management/learning-path/': typeof AuthedManagementLearningPathIndexRoute
  '/_authed/management/quiz/': typeof AuthedManagementQuizIndexRoute
  '/_authed/management/suplement/': typeof AuthedManagementSuplementIndexRoute
  '/_authed/management/tryout/': typeof AuthedManagementTryoutIndexRoute
  '/_authed/management/flashcard/$cardDeckId/add': typeof AuthedManagementFlashcardCardDeckIdAddRoute
  '/_authed/management/flashcard/$cardDeckId/edit': typeof AuthedManagementFlashcardCardDeckIdEditRoute
  '/_authed/management/grammar/$id/add': typeof AuthedManagementGrammarIdAddRoute
  '/_authed/management/grammar/$id/': typeof AuthedManagementGrammarIdIndexRoute
  '/_authed/management/learning-path/$id/': typeof AuthedManagementLearningPathIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/flashcard'
    | '/grammar'
    | '/leaderboard'
    | '/learning-path'
    | '/quiz'
    | '/suplement'
    | '/tryout'
    | '/administration/pricing/create'
    | '/administration/staff/create'
    | '/administration/user/create'
    | '/management/bootcamp/create'
    | '/management/flashcard/create'
    | '/management/quiz/create'
    | '/management/suplement/create'
    | '/management/tryout/create'
    | '/administration/pricing'
    | '/administration/staff'
    | '/administration/user'
    | '/management/bootcamp'
    | '/management/flashcard'
    | '/management/grammar'
    | '/management/learning-path'
    | '/management/quiz'
    | '/management/suplement'
    | '/management/tryout'
    | '/management/flashcard/$cardDeckId/add'
    | '/management/flashcard/$cardDeckId/edit'
    | '/management/grammar/$id/add'
    | '/management/grammar/$id'
    | '/management/learning-path/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/flashcard'
    | '/grammar'
    | '/leaderboard'
    | '/learning-path'
    | '/quiz'
    | '/suplement'
    | '/tryout'
    | '/administration/pricing/create'
    | '/administration/staff/create'
    | '/administration/user/create'
    | '/management/bootcamp/create'
    | '/management/flashcard/create'
    | '/management/quiz/create'
    | '/management/suplement/create'
    | '/management/tryout/create'
    | '/administration/pricing'
    | '/administration/staff'
    | '/administration/user'
    | '/management/bootcamp'
    | '/management/flashcard'
    | '/management/grammar'
    | '/management/learning-path'
    | '/management/quiz'
    | '/management/suplement'
    | '/management/tryout'
    | '/management/flashcard/$cardDeckId/add'
    | '/management/flashcard/$cardDeckId/edit'
    | '/management/grammar/$id/add'
    | '/management/grammar/$id'
    | '/management/learning-path/$id'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_auth/forgot-password/'
    | '/_auth/login/'
    | '/_auth/register/'
    | '/_authed/dashboard/'
    | '/_authed/flashcard/'
    | '/_authed/grammar/'
    | '/_authed/leaderboard/'
    | '/_authed/learning-path/'
    | '/_authed/quiz/'
    | '/_authed/suplement/'
    | '/_authed/tryout/'
    | '/_authed/administration/pricing/create'
    | '/_authed/administration/staff/create'
    | '/_authed/administration/user/create'
    | '/_authed/management/bootcamp/create'
    | '/_authed/management/flashcard/create'
    | '/_authed/management/quiz/create'
    | '/_authed/management/suplement/create'
    | '/_authed/management/tryout/create'
    | '/_authed/administration/pricing/'
    | '/_authed/administration/staff/'
    | '/_authed/administration/user/'
    | '/_authed/management/bootcamp/'
    | '/_authed/management/flashcard/'
    | '/_authed/management/grammar/'
    | '/_authed/management/learning-path/'
    | '/_authed/management/quiz/'
    | '/_authed/management/suplement/'
    | '/_authed/management/tryout/'
    | '/_authed/management/flashcard/$cardDeckId/add'
    | '/_authed/management/flashcard/$cardDeckId/edit'
    | '/_authed/management/grammar/$id/add'
    | '/_authed/management/grammar/$id/'
    | '/_authed/management/learning-path/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  AuthForgotPasswordIndexRoute: typeof AuthForgotPasswordIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/tryout/': {
      id: '/_authed/tryout/'
      path: '/tryout'
      fullPath: '/tryout'
      preLoaderRoute: typeof AuthedTryoutIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/suplement/': {
      id: '/_authed/suplement/'
      path: '/suplement'
      fullPath: '/suplement'
      preLoaderRoute: typeof AuthedSuplementIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/quiz/': {
      id: '/_authed/quiz/'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof AuthedQuizIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/learning-path/': {
      id: '/_authed/learning-path/'
      path: '/learning-path'
      fullPath: '/learning-path'
      preLoaderRoute: typeof AuthedLearningPathIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/leaderboard/': {
      id: '/_authed/leaderboard/'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthedLeaderboardIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/grammar/': {
      id: '/_authed/grammar/'
      path: '/grammar'
      fullPath: '/grammar'
      preLoaderRoute: typeof AuthedGrammarIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/flashcard/': {
      id: '/_authed/flashcard/'
      path: '/flashcard'
      fullPath: '/flashcard'
      preLoaderRoute: typeof AuthedFlashcardIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_auth/register/': {
      id: '/_auth/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgot-password/': {
      id: '/_auth/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/management/tryout/': {
      id: '/_authed/management/tryout/'
      path: '/management/tryout'
      fullPath: '/management/tryout'
      preLoaderRoute: typeof AuthedManagementTryoutIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/management/suplement/': {
      id: '/_authed/management/suplement/'
      path: '/management/suplement'
      fullPath: '/management/suplement'
      preLoaderRoute: typeof AuthedManagementSuplementIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/management/quiz/': {
      id: '/_authed/management/quiz/'
      path: '/management/quiz'
      fullPath: '/management/quiz'
      preLoaderRoute: typeof AuthedManagementQuizIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/management/learning-path/': {
      id: '/_authed/management/learning-path/'
      path: '/management/learning-path'
      fullPath: '/management/learning-path'
      preLoaderRoute: typeof AuthedManagementLearningPathIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/management/grammar/': {
      id: '/_authed/management/grammar/'
      path: '/management/grammar'
      fullPath: '/management/grammar'
      preLoaderRoute: typeof AuthedManagementGrammarIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/management/flashcard/': {
      id: '/_authed/management/flashcard/'
      path: '/management/flashcard'
      fullPath: '/management/flashcard'
      preLoaderRoute: typeof AuthedManagementFlashcardIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/management/bootcamp/': {
      id: '/_authed/management/bootcamp/'
      path: '/management/bootcamp'
      fullPath: '/management/bootcamp'
      preLoaderRoute: typeof AuthedManagementBootcampIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/administration/user/': {
      id: '/_authed/administration/user/'
      path: '/administration/user'
      fullPath: '/administration/user'
      preLoaderRoute: typeof AuthedAdministrationUserIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/administration/staff/': {
      id: '/_authed/administration/staff/'
      path: '/administration/staff'
      fullPath: '/administration/staff'
      preLoaderRoute: typeof AuthedAdministrationStaffIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/administration/pricing/': {
      id: '/_authed/administration/pricing/'
      path: '/administration/pricing'
      fullPath: '/administration/pricing'
      preLoaderRoute: typeof AuthedAdministrationPricingIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/management/tryout/create': {
      id: '/_authed/management/tryout/create'
      path: '/management/tryout/create'
      fullPath: '/management/tryout/create'
      preLoaderRoute: typeof AuthedManagementTryoutCreateRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/management/suplement/create': {
      id: '/_authed/management/suplement/create'
      path: '/management/suplement/create'
      fullPath: '/management/suplement/create'
      preLoaderRoute: typeof AuthedManagementSuplementCreateRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/management/quiz/create': {
      id: '/_authed/management/quiz/create'
      path: '/management/quiz/create'
      fullPath: '/management/quiz/create'
      preLoaderRoute: typeof AuthedManagementQuizCreateRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/management/flashcard/create': {
      id: '/_authed/management/flashcard/create'
      path: '/management/flashcard/create'
      fullPath: '/management/flashcard/create'
      preLoaderRoute: typeof AuthedManagementFlashcardCreateRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/management/bootcamp/create': {
      id: '/_authed/management/bootcamp/create'
      path: '/management/bootcamp/create'
      fullPath: '/management/bootcamp/create'
      preLoaderRoute: typeof AuthedManagementBootcampCreateRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/administration/user/create': {
      id: '/_authed/administration/user/create'
      path: '/administration/user/create'
      fullPath: '/administration/user/create'
      preLoaderRoute: typeof AuthedAdministrationUserCreateRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/administration/staff/create': {
      id: '/_authed/administration/staff/create'
      path: '/administration/staff/create'
      fullPath: '/administration/staff/create'
      preLoaderRoute: typeof AuthedAdministrationStaffCreateRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/administration/pricing/create': {
      id: '/_authed/administration/pricing/create'
      path: '/administration/pricing/create'
      fullPath: '/administration/pricing/create'
      preLoaderRoute: typeof AuthedAdministrationPricingCreateRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/management/learning-path/$id/': {
      id: '/_authed/management/learning-path/$id/'
      path: '/management/learning-path/$id'
      fullPath: '/management/learning-path/$id'
      preLoaderRoute: typeof AuthedManagementLearningPathIdIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/management/grammar/$id/': {
      id: '/_authed/management/grammar/$id/'
      path: '/management/grammar/$id'
      fullPath: '/management/grammar/$id'
      preLoaderRoute: typeof AuthedManagementGrammarIdIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/management/grammar/$id/add': {
      id: '/_authed/management/grammar/$id/add'
      path: '/management/grammar/$id/add'
      fullPath: '/management/grammar/$id/add'
      preLoaderRoute: typeof AuthedManagementGrammarIdAddRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/management/flashcard/$cardDeckId/edit': {
      id: '/_authed/management/flashcard/$cardDeckId/edit'
      path: '/management/flashcard/$cardDeckId/edit'
      fullPath: '/management/flashcard/$cardDeckId/edit'
      preLoaderRoute: typeof AuthedManagementFlashcardCardDeckIdEditRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/management/flashcard/$cardDeckId/add': {
      id: '/_authed/management/flashcard/$cardDeckId/add'
      path: '/management/flashcard/$cardDeckId/add'
      fullPath: '/management/flashcard/$cardDeckId/add'
      preLoaderRoute: typeof AuthedManagementFlashcardCardDeckIdAddRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
  AuthedFlashcardIndexRoute: typeof AuthedFlashcardIndexRoute
  AuthedGrammarIndexRoute: typeof AuthedGrammarIndexRoute
  AuthedLeaderboardIndexRoute: typeof AuthedLeaderboardIndexRoute
  AuthedLearningPathIndexRoute: typeof AuthedLearningPathIndexRoute
  AuthedQuizIndexRoute: typeof AuthedQuizIndexRoute
  AuthedSuplementIndexRoute: typeof AuthedSuplementIndexRoute
  AuthedTryoutIndexRoute: typeof AuthedTryoutIndexRoute
  AuthedAdministrationPricingCreateRoute: typeof AuthedAdministrationPricingCreateRoute
  AuthedAdministrationStaffCreateRoute: typeof AuthedAdministrationStaffCreateRoute
  AuthedAdministrationUserCreateRoute: typeof AuthedAdministrationUserCreateRoute
  AuthedManagementBootcampCreateRoute: typeof AuthedManagementBootcampCreateRoute
  AuthedManagementFlashcardCreateRoute: typeof AuthedManagementFlashcardCreateRoute
  AuthedManagementQuizCreateRoute: typeof AuthedManagementQuizCreateRoute
  AuthedManagementSuplementCreateRoute: typeof AuthedManagementSuplementCreateRoute
  AuthedManagementTryoutCreateRoute: typeof AuthedManagementTryoutCreateRoute
  AuthedAdministrationPricingIndexRoute: typeof AuthedAdministrationPricingIndexRoute
  AuthedAdministrationStaffIndexRoute: typeof AuthedAdministrationStaffIndexRoute
  AuthedAdministrationUserIndexRoute: typeof AuthedAdministrationUserIndexRoute
  AuthedManagementBootcampIndexRoute: typeof AuthedManagementBootcampIndexRoute
  AuthedManagementFlashcardIndexRoute: typeof AuthedManagementFlashcardIndexRoute
  AuthedManagementGrammarIndexRoute: typeof AuthedManagementGrammarIndexRoute
  AuthedManagementLearningPathIndexRoute: typeof AuthedManagementLearningPathIndexRoute
  AuthedManagementQuizIndexRoute: typeof AuthedManagementQuizIndexRoute
  AuthedManagementSuplementIndexRoute: typeof AuthedManagementSuplementIndexRoute
  AuthedManagementTryoutIndexRoute: typeof AuthedManagementTryoutIndexRoute
  AuthedManagementFlashcardCardDeckIdAddRoute: typeof AuthedManagementFlashcardCardDeckIdAddRoute
  AuthedManagementFlashcardCardDeckIdEditRoute: typeof AuthedManagementFlashcardCardDeckIdEditRoute
  AuthedManagementGrammarIdAddRoute: typeof AuthedManagementGrammarIdAddRoute
  AuthedManagementGrammarIdIndexRoute: typeof AuthedManagementGrammarIdIndexRoute
  AuthedManagementLearningPathIdIndexRoute: typeof AuthedManagementLearningPathIdIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
  AuthedFlashcardIndexRoute: AuthedFlashcardIndexRoute,
  AuthedGrammarIndexRoute: AuthedGrammarIndexRoute,
  AuthedLeaderboardIndexRoute: AuthedLeaderboardIndexRoute,
  AuthedLearningPathIndexRoute: AuthedLearningPathIndexRoute,
  AuthedQuizIndexRoute: AuthedQuizIndexRoute,
  AuthedSuplementIndexRoute: AuthedSuplementIndexRoute,
  AuthedTryoutIndexRoute: AuthedTryoutIndexRoute,
  AuthedAdministrationPricingCreateRoute:
    AuthedAdministrationPricingCreateRoute,
  AuthedAdministrationStaffCreateRoute: AuthedAdministrationStaffCreateRoute,
  AuthedAdministrationUserCreateRoute: AuthedAdministrationUserCreateRoute,
  AuthedManagementBootcampCreateRoute: AuthedManagementBootcampCreateRoute,
  AuthedManagementFlashcardCreateRoute: AuthedManagementFlashcardCreateRoute,
  AuthedManagementQuizCreateRoute: AuthedManagementQuizCreateRoute,
  AuthedManagementSuplementCreateRoute: AuthedManagementSuplementCreateRoute,
  AuthedManagementTryoutCreateRoute: AuthedManagementTryoutCreateRoute,
  AuthedAdministrationPricingIndexRoute: AuthedAdministrationPricingIndexRoute,
  AuthedAdministrationStaffIndexRoute: AuthedAdministrationStaffIndexRoute,
  AuthedAdministrationUserIndexRoute: AuthedAdministrationUserIndexRoute,
  AuthedManagementBootcampIndexRoute: AuthedManagementBootcampIndexRoute,
  AuthedManagementFlashcardIndexRoute: AuthedManagementFlashcardIndexRoute,
  AuthedManagementGrammarIndexRoute: AuthedManagementGrammarIndexRoute,
  AuthedManagementLearningPathIndexRoute:
    AuthedManagementLearningPathIndexRoute,
  AuthedManagementQuizIndexRoute: AuthedManagementQuizIndexRoute,
  AuthedManagementSuplementIndexRoute: AuthedManagementSuplementIndexRoute,
  AuthedManagementTryoutIndexRoute: AuthedManagementTryoutIndexRoute,
  AuthedManagementFlashcardCardDeckIdAddRoute:
    AuthedManagementFlashcardCardDeckIdAddRoute,
  AuthedManagementFlashcardCardDeckIdEditRoute:
    AuthedManagementFlashcardCardDeckIdEditRoute,
  AuthedManagementGrammarIdAddRoute: AuthedManagementGrammarIdAddRoute,
  AuthedManagementGrammarIdIndexRoute: AuthedManagementGrammarIdIndexRoute,
  AuthedManagementLearningPathIdIndexRoute:
    AuthedManagementLearningPathIdIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  AuthForgotPasswordIndexRoute: AuthForgotPasswordIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
